"""add_explanation_human_and_risk_note_to_strategies

Revision ID: 02a81c3db86f
Revises: 83cd2f7ef708
Create Date: 2025-11-24 21:55:11.171541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02a81c3db86f'
down_revision: Union[str, None] = '83cd2f7ef708'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_strategies', sa.Column('explanation_human', sa.Text(), nullable=True))
    op.add_column('user_strategies', sa.Column('risk_note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_strategies', 'risk_note')
    op.drop_column('user_strategies', 'explanation_human')
    # ### end Alembic commands ###

