"""add_strategy_status_and_metrics

Revision ID: 06fdd27909d9
Revises: 0675ab133e00
Create Date: 2025-11-18 21:51:40.630386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06fdd27909d9'
down_revision: Union[str, None] = '0675ab133e00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add status column as nullable first
    op.add_column('user_strategies', sa.Column('status', sa.String(length=32), nullable=True))
    # Set default value for existing rows
    op.execute("UPDATE user_strategies SET status = 'experiment' WHERE status IS NULL")
    # Now make it NOT NULL
    op.alter_column('user_strategies', 'status', nullable=False, server_default='experiment')
    op.add_column('user_strategies', sa.Column('train_metrics', sa.JSON(), nullable=True))
    op.add_column('user_strategies', sa.Column('test_metrics', sa.JSON(), nullable=True))
    # Add evolution_attempts as nullable first
    op.add_column('user_strategies', sa.Column('evolution_attempts', sa.Integer(), nullable=True))
    # Set default value for existing rows
    op.execute("UPDATE user_strategies SET evolution_attempts = 0 WHERE evolution_attempts IS NULL")
    # Now make it NOT NULL
    op.alter_column('user_strategies', 'evolution_attempts', nullable=False, server_default='0')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_strategies', 'evolution_attempts')
    op.drop_column('user_strategies', 'test_metrics')
    op.drop_column('user_strategies', 'train_metrics')
    op.drop_column('user_strategies', 'status')
    # ### end Alembic commands ###

