"""Add Strategy Engine models (UserStrategy, StrategyBacktest, StrategyLineage)

Revision ID: 156bb22043d1
Revises: 224fc197ed73
Create Date: 2025-11-17 19:55:04.218404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '156bb22043d1'
down_revision: Union[str, None] = '224fc197ed73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Use existing assettype enum (created in trades migration)
    # Reference it without trying to create it
    assettype_enum = postgresql.ENUM('STOCK', 'CRYPTO', 'FOREX', 'OTHER', name='assettype', create_type=False)
    
    op.create_table('user_strategies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('ruleset', sa.JSON(), nullable=False),
    sa.Column('asset_type', assettype_enum, nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('last_backtest_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_backtest_results', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_strategies_id'), 'user_strategies', ['id'], unique=False)
    op.create_index(op.f('ix_user_strategies_name'), 'user_strategies', ['name'], unique=False)
    op.create_index(op.f('ix_user_strategies_user_id'), 'user_strategies', ['user_id'], unique=False)
    op.create_table('strategy_backtests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('strategy_id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=16), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_return', sa.Float(), nullable=False),
    sa.Column('win_rate', sa.Float(), nullable=False),
    sa.Column('max_drawdown', sa.Float(), nullable=False),
    sa.Column('avg_pnl', sa.Float(), nullable=False),
    sa.Column('total_trades', sa.Integer(), nullable=False),
    sa.Column('sharpe_ratio', sa.Float(), nullable=True),
    sa.Column('results', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['user_strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_backtests_id'), 'strategy_backtests', ['id'], unique=False)
    op.create_index(op.f('ix_strategy_backtests_strategy_id'), 'strategy_backtests', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_strategy_backtests_symbol'), 'strategy_backtests', ['symbol'], unique=False)
    op.create_table('strategy_lineage',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('parent_strategy_id', sa.String(), nullable=False),
    sa.Column('child_strategy_id', sa.String(), nullable=False),
    sa.Column('mutation_type', sa.String(length=64), nullable=False),
    sa.Column('mutation_params', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['child_strategy_id'], ['user_strategies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_strategy_id'], ['user_strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_lineage_child_strategy_id'), 'strategy_lineage', ['child_strategy_id'], unique=False)
    op.create_index(op.f('ix_strategy_lineage_id'), 'strategy_lineage', ['id'], unique=False)
    op.create_index(op.f('ix_strategy_lineage_parent_strategy_id'), 'strategy_lineage', ['parent_strategy_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_strategy_lineage_parent_strategy_id'), table_name='strategy_lineage')
    op.drop_index(op.f('ix_strategy_lineage_id'), table_name='strategy_lineage')
    op.drop_index(op.f('ix_strategy_lineage_child_strategy_id'), table_name='strategy_lineage')
    op.drop_table('strategy_lineage')
    op.drop_index(op.f('ix_strategy_backtests_symbol'), table_name='strategy_backtests')
    op.drop_index(op.f('ix_strategy_backtests_strategy_id'), table_name='strategy_backtests')
    op.drop_index(op.f('ix_strategy_backtests_id'), table_name='strategy_backtests')
    op.drop_table('strategy_backtests')
    op.drop_index(op.f('ix_user_strategies_user_id'), table_name='user_strategies')
    op.drop_index(op.f('ix_user_strategies_name'), table_name='user_strategies')
    op.drop_index(op.f('ix_user_strategies_id'), table_name='user_strategies')
    op.drop_table('user_strategies')
    # ### end Alembic commands ###

