"""Add OAuth fields and EmailOTP table

Revision ID: 2611532bb11b
Revises: 846cf707ea97
Create Date: 2025-11-18 18:40:46.376907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2611532bb11b'
down_revision: Union[str, None] = '846cf707ea97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_otps',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('otp_code', sa.String(length=6), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_otps_email'), 'email_otps', ['email'], unique=False)
    op.create_index(op.f('ix_email_otps_id'), 'email_otps', ['id'], unique=False)
    op.add_column('group_members', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('group_messages', sa.Column('message_type', sa.String(length=32), nullable=True))
    op.add_column('users', sa.Column('auth_provider', sa.String(length=32), nullable=True))
    op.add_column('users', sa.Column('provider_id', sa.String(length=255), nullable=True))
    # Add email_verified as nullable first, then set default for existing rows, then make NOT NULL
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=True, server_default='false'))
    # Update existing rows to have email_verified = false (for email users) or true (if they have OAuth)
    op.execute("UPDATE users SET email_verified = false WHERE email_verified IS NULL")
    # Now make it NOT NULL
    op.alter_column('users', 'email_verified', nullable=False, server_default='false')
    op.create_index(op.f('ix_users_auth_provider'), 'users', ['auth_provider'], unique=False)
    op.create_index(op.f('ix_users_provider_id'), 'users', ['provider_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_provider_id'), table_name='users')
    op.drop_index(op.f('ix_users_auth_provider'), table_name='users')
    op.drop_column('users', 'email_verified')
    op.drop_column('users', 'provider_id')
    op.drop_column('users', 'auth_provider')
    op.drop_column('group_messages', 'message_type')
    op.drop_column('group_members', 'created_at')
    op.drop_index(op.f('ix_email_otps_id'), table_name='email_otps')
    op.drop_index(op.f('ix_email_otps_email'), table_name='email_otps')
    op.drop_table('email_otps')
    # ### end Alembic commands ###

