"""Add plan_code and royalty fields to subscription plans, add current_plan_id to users

Revision ID: 2ac8bfa6e472
Revises: fd9605a69669
Create Date: 2025-11-16 22:06:03.342836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ac8bfa6e472'
down_revision: Union[str, None] = 'fd9605a69669'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription_plans', sa.Column('plan_code', sa.String(length=64), nullable=False))
    op.add_column('subscription_plans', sa.Column('default_royalty_percent', sa.Float(), nullable=False))
    op.create_index(op.f('ix_subscription_plans_plan_code'), 'subscription_plans', ['plan_code'], unique=True)
    op.add_column('users', sa.Column('current_plan_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('royalty_percent', sa.Float(), nullable=True))
    op.create_index(op.f('ix_users_current_plan_id'), 'users', ['current_plan_id'], unique=False)
    op.create_foreign_key(None, 'users', 'subscription_plans', ['current_plan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_current_plan_id'), table_name='users')
    op.drop_column('users', 'royalty_percent')
    op.drop_column('users', 'current_plan_id')
    op.drop_index(op.f('ix_subscription_plans_plan_code'), table_name='subscription_plans')
    op.drop_column('subscription_plans', 'default_royalty_percent')
    op.drop_column('subscription_plans', 'plan_code')
    # ### end Alembic commands ###

