"""add_platform_fee_percent_to_subscription_plans

Revision ID: 6aec9b694526
Revises: 06fdd27909d9
Create Date: 2025-11-18 22:42:23.332368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6aec9b694526'
down_revision: Union[str, None] = '06fdd27909d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add platform_fee_percent as nullable first
    op.add_column('subscription_plans', sa.Column('platform_fee_percent', sa.Float(), nullable=True))
    # Set default values based on plan_code
    op.execute("""
        UPDATE subscription_plans 
        SET platform_fee_percent = CASE 
            WHEN plan_code = 'USER' THEN 7.0
            WHEN plan_code = 'USER_PLUS_UPLOAD' THEN 5.0
            WHEN plan_code = 'CREATOR' THEN 3.0
            ELSE 5.0
        END
        WHERE platform_fee_percent IS NULL
    """)
    # Now make it NOT NULL
    op.alter_column('subscription_plans', 'platform_fee_percent', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription_plans', 'platform_fee_percent')
    # ### end Alembic commands ###

