"""add_group_strategy_functionality

Revision ID: 7670e28d4607
Revises: 7f7a5a6ca405
Create Date: 2025-11-25 16:22:11.231315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7670e28d4607'
down_revision: Union[str, None] = '7f7a5a6ca405'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_messages', sa.Column('strategy_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_group_messages_strategy_id'), 'group_messages', ['strategy_id'], unique=False)
    op.create_foreign_key(None, 'group_messages', 'user_strategies', ['strategy_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'group_messages', type_='foreignkey')
    op.drop_index(op.f('ix_group_messages_strategy_id'), table_name='group_messages')
    op.drop_column('group_messages', 'strategy_id')
    # ### end Alembic commands ###

