"""Add user trading settings and enhance strategy lineage with royalties

Revision ID: 846cf707ea97
Revises: 156bb22043d1
Create Date: 2025-11-17 21:45:14.155257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '846cf707ea97'
down_revision: Union[str, None] = '156bb22043d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_trading_settings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('min_balance', sa.Float(), nullable=False),
    sa.Column('max_auto_trade_amount', sa.Float(), nullable=False),
    sa.Column('max_risk_percent', sa.Float(), nullable=False),
    sa.Column('capital_range_min', sa.Float(), nullable=True),
    sa.Column('capital_range_max', sa.Float(), nullable=True),
    sa.Column('auto_execution_enabled', sa.Boolean(), nullable=False),
    sa.Column('stop_under_balance', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_trading_settings_id'), 'user_trading_settings', ['id'], unique=False)
    op.create_index(op.f('ix_user_trading_settings_user_id'), 'user_trading_settings', ['user_id'], unique=True)
    op.add_column('strategy_lineage', sa.Column('similarity_score', sa.Float(), nullable=True))
    op.add_column('strategy_lineage', sa.Column('creator_user_id', sa.String(), nullable=True))
    op.add_column('strategy_lineage', sa.Column('royalty_percent_parent', sa.Float(), nullable=True))
    op.add_column('strategy_lineage', sa.Column('royalty_percent_child', sa.Float(), nullable=True))
    op.create_index(op.f('ix_strategy_lineage_creator_user_id'), 'strategy_lineage', ['creator_user_id'], unique=False)
    op.create_foreign_key(None, 'strategy_lineage', 'users', ['creator_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'strategy_lineage', type_='foreignkey')
    op.drop_index(op.f('ix_strategy_lineage_creator_user_id'), table_name='strategy_lineage')
    op.drop_column('strategy_lineage', 'royalty_percent_child')
    op.drop_column('strategy_lineage', 'royalty_percent_parent')
    op.drop_column('strategy_lineage', 'creator_user_id')
    op.drop_column('strategy_lineage', 'similarity_score')
    op.drop_index(op.f('ix_user_trading_settings_user_id'), table_name='user_trading_settings')
    op.drop_index(op.f('ix_user_trading_settings_id'), table_name='user_trading_settings')
    op.drop_table('user_trading_settings')
    # ### end Alembic commands ###

