"""Add join_code field to groups table

Revision ID: a9139906eddd
Revises: 2ac8bfa6e472
Create Date: 2025-11-17 18:08:47.575929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9139906eddd'
down_revision: Union[str, None] = '2ac8bfa6e472'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('join_code', sa.String(length=10), nullable=False))
    op.alter_column('groups', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_index(op.f('ix_groups_join_code'), 'groups', ['join_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_groups_join_code'), table_name='groups')
    op.alter_column('groups', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('groups', 'join_code')
    # ### end Alembic commands ###

