"""add_user_agreement_table

Revision ID: e30aeaee520b
Revises: 7670e28d4607
Create Date: 2025-12-03 22:24:08.215447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e30aeaee520b'
down_revision: Union[str, None] = '7670e28d4607'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_agreements',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('agreement_type', sa.String(length=64), nullable=False),
    sa.Column('agreement_version', sa.String(length=32), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_agreements_id'), 'user_agreements', ['id'], unique=False)
    op.create_index(op.f('ix_user_agreements_user_id'), 'user_agreements', ['user_id'], unique=False)
    op.add_column('admin_settings', sa.Column('max_concurrent_backtests', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_trades_mode'), 'trades', ['mode'], unique=False)
    op.create_index(op.f('ix_trades_opened_at'), 'trades', ['opened_at'], unique=False)
    op.create_index(op.f('ix_trades_status'), 'trades', ['status'], unique=False)
    op.create_index(op.f('ix_user_strategies_last_backtest_at'), 'user_strategies', ['last_backtest_at'], unique=False)
    op.create_index(op.f('ix_user_strategies_status'), 'user_strategies', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_strategies_status'), table_name='user_strategies')
    op.drop_index(op.f('ix_user_strategies_last_backtest_at'), table_name='user_strategies')
    op.drop_index(op.f('ix_trades_status'), table_name='trades')
    op.drop_index(op.f('ix_trades_opened_at'), table_name='trades')
    op.drop_index(op.f('ix_trades_mode'), table_name='trades')
    op.drop_column('admin_settings', 'max_concurrent_backtests')
    op.drop_index(op.f('ix_user_agreements_user_id'), table_name='user_agreements')
    op.drop_index(op.f('ix_user_agreements_id'), table_name='user_agreements')
    op.drop_table('user_agreements')
    # ### end Alembic commands ###

